packages:
  - ./client/frontend
  - ./cdk
  - ./server

onlyBuiltDependencies:
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild
  - mongodb-memory-server

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  validator@<13.15.20: '>=13.15.20'
