name: Build and Dist for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} # Ensure GH_TOKEN is set in your repository secrets.
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Run Build Command
        run: npm run build

      - name: Run Dist Command
        run: npm run dist
